version: 2
jobs:
  test_npm:
    docker:
      - image: node:8.9.4
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -y shellcheck

      - run:
          name: Test npm install and ensure scripts are added to path
          command: |
            npm install -g git://github.com/reactiveops/rok8s-scripts.git#${CIRCLE_SHA1}

      - run:
          name: Run Shellcheck
          command: |
            shellcheck bin/docker-* \
              bin/install-rok8s-requirements \
              bin/k8s-apply \
              bin/verify-deployment \
              bin/k8s-lint \
              bin/prepare-* \
              bin/helm-*

      - run:
          name: Run basic linting
          command: |
            cd examples/production-ready
            k8s-lint -f staging.config
            k8s-lint -f production.config

  test_pip:
    environment:
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/google-cloud-sdk/bin

    docker:
      - image: python:2.7
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -y shellcheck

      - run:
          name: Test pip install and ensure scripts are added to path
          command: |
            pip install git+https://github.com/reactiveops/rok8s-scripts.git@$CIRCLE_SHA1

      - run:
          name: Run Shellcheck
          command: |
            shellcheck bin/docker-* \
              bin/install-rok8s-requirements \
              bin/k8s-apply \
              bin/verify-deployment \
              bin/k8s-lint \
              bin/prepare-* \
              bin/helm-*

      - run:
          name: Run basic linting
          command: |
            cd examples/production-ready
            k8s-lint -f staging.config
            k8s-lint -f production.config

  release:
    environment:
      GITHUB_ORGANIZATION: $CIRCLE_PROJECT_USERNAME
      GITHUB_REPOSITORY: $CIRCLE_PROJECT_REPONAME
    docker:
      - image: node:8.9.4
    steps:
      - checkout

      - run:
          name: Load NPM Credentials
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc

      - run:
          name: NPM release
          command: |
            echo $CIRCLE_TAG | xargs npm version --no-git-tag-version
            npm publish

      - run:
          name: GitHub release
          command: |
            git fetch --tags
            curl -O https://raw.githubusercontent.com/reactiveops/release.sh/v0.0.2/release
            /bin/bash release


workflows:
  version: 2
  test:
    jobs:
      - test_npm
      - test_pip
  release:
    jobs:
      - release:
          filters:
            tags:
              only: /^v*/
            branches:
              ignore: /.*/
