apiVersion: batch/v1
kind: Job
metadata:
  name: example-app
spec:
  template:
    metadata:
      name: busybox
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["/bin/sh", "-c", "sleep 20"]
      restartPolicy: Never
